server:
  port: 8988

spring:
  zipkin:
    base-url: http://localhost:9411

  application:
    name: service-zipkin-hi

##11111111111
#通过引入spring-cloud-starter-zipkin依赖和设置spring.zipkin.base-url就可以了


##在spring Cloud为F版本的时候，已经不需要自己构建Zipkin Server了，只需要下载jar即可，下载地址：
  #
  #https://dl.bintray.com/openzipkin/maven/io/zipkin/java/zipkin-server/

  #java -jar zipkin-server-2.10.1-exec.jar

  #localhost:9411

  #新建service-zipkin-hi和service-zipkin-miya互相调用