##仅仅@EnableEurekaClient是不够的，还需要在配置文件中注明自己的服务注册中心的地址

server:
  port: 8762


##需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
spring:
  application:
    name: service-hi
##http://localhost:8761/eureka/
##高可用配置http://peer1:8761/eureka/
##改hosts文件：127.0.0.1 peer1
  #127.0.0.1 peer2
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"